config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :sitios do
    resources :reviews
  end
  root 'sitios#index'
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :sitio
  belongs_to :user
end

app/models/sitio.rb
class Sitio < ActiveRecord::Base
  belongs_to :user
  has_many :reviews

  has_attached_file :sitio_img, styles: { sitio_index: "250x350>", sitio_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :sitio_img, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sitios
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_sitio
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @review = Review.new
  end
  def create
    @review = Review.new(review_params)
    @review.sitio_id = @sitio.id
    @review.user_id  = current_user.id

    if @review.save
      redirect_to sitio_path(@sitio)
    else
      render 'new'
    end
  end
  def edit
  end
  def update
    if @review.update(review_params)
      redirect_to sitio_path(@sitio)
    else
      render 'edit'
    end
  end
  def destroy
    @review.destroy
    redirect_to sitio_path(@sitio)
  end

  private
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
    def find_sitio
      @sitio = Sitio.find(params[:sitio_id])
    end
    def find_review
      @review = Review.find(params[:id])
    end

end

app/controllers/sitios_controller.rb
class SitiosController < ApplicationController
  before_action :find_sitio, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    @sitios = Sitio.all.order("created_at ASC")
  end

  def show
    if @sitio.reviews.blank?
      @average_review = 0
    else
      @average_review = @sitio.reviews.average(:rating).round(2)
    end
  end

  def new
    @sitio = current_user.sitios.build
  end

  def create
    @sitio = current_user.sitios.build(sitio_params)
    if @sitio.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @sitio.update(sitio_params)
      redirect_to sitio_path(@sitio)
    else
      render 'edit'
    end
  end

  def destroy
    @sitio.destroy
    redirect_to root_path
  end

  private
  def sitio_params
    params.require(:sitio).permit(:title, :description, :author, :sitio_img)
  end
  def find_sitio
    @sitio = Sitio.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sitios_helper.rb
module SitiosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Red de amigos por chiapas</title>
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0,
  maximum-scale=1.0, minimum-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="jquery.js"></script>
  <script src="script_menu.js"></script>
</head>
<body>
  <header>
    <nav>
      <ul>
        <li><%= link_to "Inicio", root_path%></li>
        <li><%= link_to "Contáctanos", new_user_registration_path %></li>
      </ul>

      <%= link_to image_tag("LogoRedAmigoscv.png", id: "logo"), root_path %>

      <ul>
        <% if user_signed_in? %>
          <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Afiliarse", new_user_registration_path %></li>
          <li><%= link_to "Ingresar", new_user_session_path %></li>
        <% end %>
      </ul>
      <ul >
        <% if user_signed_in? %>
        <li><%= link_to "Agregar Sitio", new_sitio_path %></li>
        <% end %>
      </ul>
    </nav>
  </header>

  <section id="banner"></section>
  <section id="cuerpo">
  </section>
    <article class="">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </article>

    <div class="container">
      <%= yield %>
    </div>

    <footer class="main-footer">
      <div class="creditos">
        <p >Red de Amigos por Chiapas &copy; 2017 | diseño: </p>
        <div id="telefono">
          <%= link_to image_tag("LogoACL_tv.png", class: "logoacl"), "https://www.facebook.com/Alexis.Crouz" %><p> @acruzlara </p>
        </div>
      </div>
      <div class="medio">
        <p>Dirección:</p>
        <p>Tuxtla Gutiérrez, Chiapas, México</p>
        <p>5a. Oriente Norte, Edificio A, Planta Baja 2,</p>
        <p>Unidad Quetzalcoatl</p>
      </div>
      <div class="sociales">
        <%= link_to image_tag("facebook.png", class: "logos"), "https://www.facebook.com/Red.de.Amigos.por.Chiapas" %>
        <%= link_to image_tag("twitter2.png", class: "logos"), "https://twitter.com/reddeamigosxchs" %>
        <%= link_to image_tag("youtube.png", class: "logos"), "#" %>
        <%= link_to image_tag("google2.png", class: "logos"), "#" %>
        <%= link_to image_tag("linkedin.png", class: "logos"), "http://planeacion.sep.gob.mx/SIC/" %>
        <div id="telefono">
          <%= link_to image_tag("whatsappv1.png", class: "logos"), "https://web.whatsapp.com/" %><p>961.579.10.83</p>
        </div>
      </div>

    </footer>

  <!--
    <div class="slider">
      <ul>
        <li><%= image_tag "img/Logo.png" %></li>
        <li><%= image_tag "img/foto1.jpg" %></li>
        <li><%= image_tag "img/foto2.jpg" %></li>
        <li><%= image_tag "img/foto3.jpg" %></li>
        <li><%= image_tag "img/foto4.jpg" %></li>
        <li><%= image_tag "img/foto5.jpg" %></li>
      </ul>
    </div>
  -->

  <script src="jquery.js"></script>
  <script src="script_menu.js"></script>

</body>
</html>

app/views/layouts/application_Modif.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <title>Red de amigos por chiapas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="jquery.js" charset="utf-8"></script>
</head>
<body>
  <header class="main-header">
    <div class="ed-container">
      <%= link_to root_path do %>
      <%= image_tag "LogoRedAmigos_ico.png", width: 120, height: 60, class: "logo" %>
      <% end %>
    </div>
    <div class="ed-item s-30 l-70 cross-center main-end">
      <div class="nav-toggle" id="nav-toggle"></div>
        <nav class="main-nav" id="menu">
          <ul class="main-menu" id="menu">
            <% if user_signed_in? %>
              <li class="main-menu__item"><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li class="main-menu__item"><%= link_to "Afiliarse", new_user_registration_path %></li>
              <li class="main-menu__item"><%= link_to "Ingresar", new_user_session_path %></li>
            <% end %>
          </ul>
          <ul class="main-menu-right" id="menu">
            <% if user_signed_in? %>
              <li class="main-menu__item"><%=  %></li>
              <li class="main-menu__item"><%= link_to "Agregar Sitio", new_sitio_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </header>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="ed-container">
    <%= yield %>
  </div>

  <script src="sticky.js"></script>
  <script src="ed-grid.js"></script>
  <script>
    edgrid.menu('nav', 'menu')
  </script>
</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@sitio, @sitio.reviews.build]) do |f| %>
  <div id="rating-form">
    <label for="">Calificar </label>
<!--    <%= f.input :rating %> -->
  </div>
  <%= f.input :comment %>
  <%= f.button :submit, class: "btn-custom2" %>
<% end %>

<script>
  $('#rating-form').raty({
    path: '/assets',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<div class="review">
  <!-- <p><%= review.rating %></p> -->
  <div class="review-rating" data-score="<%= review.rating %>" ></div>
  <p><%= review.comment %></p>

  <% if user_signed_in? %>
    <% if review.user_id == current_user.id %>
      <div class="links btn-group">
        <%= link_to "Borrar", sitio_review_path(review.sitio, review), method: :delete, data: { confirm: "Está seguro?"}, class: "btn btn-custom" %>
        <%= link_to "Editar", edit_sitio_review_path(review.sitio, review), class: "btn btn-custom" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="edit-review-form">

    <h1>Editar Comentario</h1>

    <%= simple_form_for([@sitio, @review]) do |f| %>
      <div id="rating-form">
        <label>Calificar</label>
      </div>
      <%= f.input :comment %>
      <%= f.button :submit, class: "btn-custom2" %>
    <% end %>
  </div>
</div>

<script>
  $('#rating-form').raty({
    path: '/assets',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="new-review-form">

    <h1>Nuevo Comentario</h1>

    <%= render "form" %>

  </div>
</div>

app/views/sitios/_form.html.erb
<%= simple_form_for @sitio, html: { :multipart => true } do |f| %>
  <%= f.file_field :sitio_img %>
  <%= f.input :title, label: "Nombre del Sitio" %>
  <%= f.input :description %>
  <%= f.input :author %>
  <%= f.button :submit, class: "btn-custom2" %>
<% end %>

app/views/sitios/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="edit-sitio-form">
    <h1>Editar Sitios</h1>

    <%= simple_form_for @sitio, html: { :multipart => true } do |f| %>
      <%= f.file_field :sitio_img %>
      <%= f.input :title, label: "Nombre del Sitio" %>
      <%= f.input :description %>
      <%= f.input :author %>
      <%= f.button :submit, class: "btn-custom2" %>
    <% end %>
  </div>
</div>

app/views/sitios/index.html.erb
<div class="row">
  <% @sitios.each do |sitio| %>
    <div class="col-md-4">
      <a href="/sitios/<%= sitio.id %>">
        <%= image_tag sitio.sitio_img.url(:sitio_index), class: "sitio" %>
      </a>
    </div>
  <% end %>
</div>

app/views/sitios/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="new-sitio-form">

    <h1>Nuevo Sitio</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/sitios/show.html.erb
<div class="row">
  <div class="col-md-5">
    <%= image_tag @sitio.sitio_img.url(:sitio_show), class: "sitio-show" %>
  </div>
  <div class="col-md-7">
    <div class="sitio-info">
      <h2 class="sitio-title"><%= @sitio.title %></h2>
      <div class="average-review-rating" data-score=<%= @average_review %>></div>
      <span class="number-of-reviews">Con base a <%= @sitio.reviews.count %> comentarios</span>
      <p class="sitio-desc"><%= @sitio.description %></p>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-5">
    <!-- Comentarios y raiting van acá -->
    <div class="reviews">
      <h3>Comentarios</h3>
      <%= render @sitio.reviews %>
      <div>
        <%= link_to "Agregar Comentario", new_sitio_review_path(@sitio), class: "btn-custom" %>
      </div>
    </div>
  </div>
</div>

<div class="links btn-group">
  <%= link_to "Regresar", root_path, class: "btn btn-custom" %>

  <% if user_signed_in? %>
  <% if @sitio.user_id == current_user.id %>
  <%= link_to "Editar", edit_sitio_path(@sitio), class: "btn btn-custom" %>
  <%= link_to "Borrar", sitio_path(@sitio), method: :delete, data: { confirm: "Está seguro de borrar?"}, class: "btn btn-custom" %>
  <% end %>
  <% end %>

</div>

<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function(){
      return $(this).attr('data-score');
    },
    path: '/assets'
  });
</script>
<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets',
    score: function(){
      return $(this).attr('data-score')
    }
  });
</script>